### ISSUE TITLE
エラーハンドリングまわりの修正

### ISSUE THREAD

**Issue by SakagamiKazuto** [SakagamiKazuto/golang_api#5]
現状
handlerロジック内にエラー時の処理も混在していて
エラーとして返す型やメッセージなどが属人的になりやすい

**Comment by SakagamiKazuto** [comment]
理想
エラー自体が発生しうる問題を網羅していて、
その上でエラーが起きた場所でのエラーがメッセージとして確認出来る

handlerで直したい部分と解決策
1. DBのロジックがhandleに漏れている
    1. DBに移行
2. エラーのstatusやロジックが管理しやすいように
    1. errorhandleの構造体別で作る
3. エラーの種類で分岐することが可能
    1. interfaceを活用する
4. 内部エラーloggerが出力されない
    1. loggerを導入する
5. ログインチェック毎回 ← ※ここでHTTPErrorに渡すという発想なら必須ではない

仕様
種類
1. 内部起因エラー
        1. メッセは簡素
        2. ログは詳細
2. 外部起因エラー
        1. メッセは詳細
        2. ログは簡素

メッセージ
1. 場所
    1. ファイル名・行
2. 理由
    1. オリジナルメッセージ

**Comment by SakagamiKazuto** [comment]
↑ 4. 内部エラーの確認が難しいについて
**現状のログ**
 **例1 型周りで発生したエラーについてのログ**
{“time":"2021-04-04T11:03:34.3993344Z","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] invalid WriteHeader code 0 goroutine 7 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0xc44a10, 0x1000, 0x1004a0000, 0xc8ab18, 0xc000108a80)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/middleware/recover.go:71 +0x166\npanic(0xb57740, 0xc00001e0b0)\n\t/usr/local/go/src/runtime/panic.go:971 +0x4c7\nnet/http.checkWriteHeaderCode(0x0)\n\t/usr/local/go/src/net/http/server.go:1112 +0x168\nnet/http.(*response).WriteHeader(0xc0000200e0, 0x0)\n\t/usr/local/go/src/net/http/server.go:1146 +0x51b\ngithub.com/labstack/echo/v4.(*Response).WriteHeader(0xc000058de0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/response.go:63 +0x1a6\ngithub.com/labstack/echo/v4.(*context).json(0xc000108a80, 0x0, 0xb3ff00, 0xc00020c020, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/context.go:433 +0xe8\ngithub.com/labstack/echo/v4.(*context).JSON(0xc000108a80, 0x0, 0xb3ff00, 0xc00020c020, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/context.go:442 +0x11b\ngithub.com/SakagamiKazuto/golang_api/apperror.(*ErrorContext).ResponseError(0xc0002312e0, 0xc7d220, 0xc0000907b0, 0x0, 0x0)\n\t/go/src/apperror/error.go:21 +0x25d\ngithub.com/SakagamiKazuto/golang_api/handler.Signup(0xc8ab18, 0xc000108a80, 0x0, 0x0)\n\t/go/src/handler/auth.go:52 +0x377\ngithub.com/labstack/echo/v4.(*Echo).Add.func1(0xc8ab18, 0xc000108a80, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/echo.go:490 +0xce\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0xc8ab18, 0xc000108a80, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/middleware/recover.go:78 +0x1d5\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0xc8ab18, 0xc000108a80, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/middleware/logger.go:118 +0x1a2\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000a1e0, 0xc83b40, 0xc0000200e0, 0xc000176a00)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/echo.go:593 +0x1fe\nnet/http.serverHandler.ServeHTTP(0xc00008e2a0, 0xc83b40, 0xc0000200e0, 0xc000176a00)\n\t/usr/local/go/src/net/http/server.go:2887 +0x22b\nnet/http.(*conn).serve(0xc00010d900, 0xc84af8, 0xc0000a0440)\n\t/usr/local/go/src/net/http/server.go:1952 +0x1c25\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3013 +0x96e\n\ngoroutine 1 [IO wait, 2 minutes]:\ninternal/poll.runtime_pollWait(0x7f0255af2900, 0x72, 0x0)\n\t/usr/local/go/src/runtime/netpoll.go:222 +0x65\ninternal/poll.(*pollDesc).wait(0xc00018fc98, 0x72, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b\ninternal/poll.(*pollDesc).waitRead(0xc00018fc98, 0xffffffffffffff00, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:92 +0x45\ninternal/poll.(*FD).Accept(0xc00018fc80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/fd_unix.go:401 +0x467\nnet.(*netFD).accept(0xc00018fc80, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/net/fd_unix.go:172 +0x85\nnet.(*TCPListener).accept(0xc0000a2930, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/net/tcpsock_posix.go:139 +0x65\nnet.(*TCPListener).AcceptTCP(0xc0000a2930, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/net/tcpsock.go:248 +0x79\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept(0xc0000a2930, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/echo.go:767 +0x50\nnet/http.(*Server).Serve(0xc00008e2a0, 0xc83450, 0xc00009a148, 0x0, 0x0)\n\t/usr/local/go/src/net/http/server.go:2981 +0x42c\ngithub.com/labstack/echo/v4.(*Echo).StartServer(0xc00000a1e0, 0xc00008e2a0, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/echo.go:663 +0x607\ngithub.com/labstack/echo/v4.(*Echo).Start(0xc00000a1e0, 0xc0000984f9, 0x5, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.0.0/echo.go:604 +0x7d\nmain.main()\n\t/go/src/main.go:17 +0xb8\n\ngoroutine 20 [select, 2 minutes]:\ndatabase/sql.(*DB).connectionOpener(0xc0001de340, 0xc84af8, 0xc0002035c0)\n\t/usr/local/go/src/database/sql/sql.go:1133 +0xd0\ncreated by database/sql.OpenDB\n\t/usr/local/go/src/database/sql/sql.go:740 +0x265\n\ngoroutine 25 [runnable]:\nnet/http.(*connReader).backgroundRead(0xc0001b3e90)\n\t/usr/local/go/src/net/http/server.go:691\ncreated by net/http.\n"}
api_1  | {"time":"2021-04-04T11:03:34.4000555Z","id":"","remote_ip":"172.22.0.1","host":"localhost:9999","method":"POST","uri":"/signup","user_agent":"curl/7.64.1","status":500,"error":"","latency":1501300,"latency_human":"1.5013ms","bytes_in":63,"bytes_out":36}

**例2 DB接続でのエラー**
api_1  | goroutine 1 [running]:
api_1  | github.com/SakagamiKazuto/golang_api/db.InitDB()
api_1  |        /go/src/db/db.go:22 +0x385
api_1  | main.main()
api_1  |        /go/src/main.go:15 +0x34
